name: ecbee_test_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  qr_flutter: ^4.1.0
  geolocator: ^12.0.0
  intl_phone_number_input: ^0.7.4
  firebase_app_check: ^0.3.0+2
  android_intent: ^2.0.2
  firebase_core: ^3.1.1
  country_picker: ^2.0.26
  intl:
  jiffy: ^6.3.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  nb_utils: ^7.0.3

flutter: 
  uses-material-design: true

